### ISSUE TITLE
Google Search

### ISSUE THREAD

**Issue by dripti** [nielsbosma/SeoTools-for-Excel-Connectors#20]
Hi, 

This is an amazing connector. Although i have 2 queries  : 
1. How can i change the country for which i want these results, i think it automatically picks up the current region . 
2. How do i get more than 10 results ? I tried changing the number on the excel "max results ". However, it still gives me 10 results.

**Comment by diskborsteMC** [comment]
Hi!

1. This is a bit tricky because Google changes back to the local country by default:
https://www.thenewsminute.com/article/now-google-search-results-be-country-specific-default-70696

2. I've updated the Connector and removed a bug which prohibited you from getting more than 10 results. You can update the Connector from the Manager.
